# Generated by Django 5.0.1 on 2024-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='name',
            field=models.CharField(default='TJMC', max_length=50),
        ),
    ]
