# Generated by Django 5.0.1 on 2024-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0003_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpage',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
