# Generated by Django 5.0.1 on 2024-01-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0005_alter_frontpage_phone_number1'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='official_bearer')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
