# Generated by Django 5.0.1 on 2024-01-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0006_frontpageoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpageoffice',
            name='image',
            field=models.ImageField(upload_to='app_crud/official_bearer'),
        ),
    ]
