# Generated by Django 5.0.1 on 2024-01-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0010_frontpageoffice_leader_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpageoffice',
            name='leader_description',
        ),
    ]
