# Generated by Django 5.0.1 on 2024-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0011_remove_frontpageoffice_leader_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='latest_events/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='frontpage',
            name='phone_number3',
        ),
    ]
