# Generated by Django 5.0.1 on 2024-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0012_latestevent_remove_frontpage_phone_number3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestEvent',
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(null=True, upload_to='latest_events/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
