# Generated by Django 5.0.1 on 2024-01-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0014_rename_name_notice_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpage',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='frontpage',
            name='phone_number2',
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='phone_number1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
