# Generated by Django 5.0.1 on 2024-01-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0016_rename_phone_number1_frontpage_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrontPage',
            new_name='ContactNumber',
        ),
    ]
