# Generated by Django 5.0.1 on 2024-01-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0017_rename_frontpage_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='phone_number',
            field=models.CharField(default='No image', max_length=20, null=True),
        ),
    ]
