# Generated by Django 5.0.1 on 2024-01-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0018_alter_contactnumber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='latest_events/'),
        ),
    ]
