# Generated by Django 5.0.1 on 2024-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0019_alter_contactnumber_phone_number_alter_notice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='noimg.jpg', upload_to='college_picture/')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(upload_to='latest_events/'),
        ),
    ]
