# Generated by Django 5.0.1 on 2024-01-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0022_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_us_description',
            field=models.CharField(default='This is About Us Section.', max_length=3000),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='about_us/'),
        ),
    ]
