# Generated by Django 5.0.1 on 2024-01-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0024_alter_aboutus_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
