# Generated by Django 5.0.1 on 2024-01-15 11:08

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0029_notice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=nepali_datetime_field.models.NepaliDateField(auto_now_add=True),
        ),
    ]
