# Generated by Django 5.0.1 on 2024-01-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0031_alter_notice_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=500)),
                ('actual_file', models.FileField(upload_to='downloadable_files/')),
            ],
        ),
    ]
