# Generated by Django 5.0.1 on 2024-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0032_downloadablefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(help_text='Enter your Full Name', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='9800000000', max_length=10)),
                ('address', models.CharField(help_text='Enter Your Address', max_length=30)),
                ('message', models.CharField(help_text='Enter Your Message', max_length=300)),
            ],
        ),
    ]
