# Generated by Django 5.0.1 on 2024-01-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0033_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='fullName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='latest_events/'),
        ),
    ]
