# Generated by Django 5.0.1 on 2024-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0034_alter_contactus_address_alter_contactus_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, default='TJMC', max_length=200, null=True),
        ),
    ]
