# Generated by Django 5.0.1 on 2024-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0035_alter_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnumber',
            name='admission_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
