# Generated by Django 5.0.1 on 2024-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0036_contactnumber_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
