# Generated by Django 5.0.1 on 2024-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0037_alter_contactnumber_admission_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactnumber',
            name='admission_number',
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
