# Generated by Django 5.0.1 on 2024-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0038_admissionnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionnumber',
            name='admission_number',
            field=models.CharField(default='TJMC', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='phone_number',
            field=models.CharField(default='TJMC', max_length=20),
        ),
    ]
