# Generated by Django 5.0.1 on 2024-01-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0039_alter_admissionnumber_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, upload_to='latest_events/'),
        ),
    ]
