# Generated by Django 5.0.1 on 2024-01-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0040_alter_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='college_picture/'),
        ),
    ]
